name: GiftCode
version: '1.0.0'
main: top.wunanc.giftcode.GiftCode
api-version: '1.20'
authors: [ Wunanc ]
description: Add redeem code functionality to your server, with Folia support!
website: https://mc.wunanc.top
folia-supported: true